//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace MsDynamicsTest.MsNavInventoryReportEntry {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="InventoryReportEntry_Binding", Namespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry")]
    public partial class InventoryReportEntry_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InventoryReportEntry_Service() {
            this.Url = global::MsDynamicsTest.Properties.Settings.Default.MsDynamicsTest_MsNavInventoryReportEntry_InventoryReportEntry_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/inventoryreportentry:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("InventoryReportEntry")]
        public InventoryReportEntry Read(string Type) {
            object[] results = this.Invoke("Read", new object[] {
                        Type});
            return ((InventoryReportEntry)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string Type) {
            this.ReadAsync(Type, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string Type, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        Type}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/inventoryreportentry:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("InventoryReportEntry")]
        public InventoryReportEntry ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((InventoryReportEntry)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/inventoryreportentry:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public InventoryReportEntry[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] InventoryReportEntry_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((InventoryReportEntry[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(InventoryReportEntry_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(InventoryReportEntry_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/inventoryreportentry:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/inventoryreportentry:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/inventoryreportentry:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref InventoryReportEntry InventoryReportEntry) {
            object[] results = this.Invoke("Create", new object[] {
                        InventoryReportEntry});
            InventoryReportEntry = ((InventoryReportEntry)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(InventoryReportEntry InventoryReportEntry) {
            this.CreateAsync(InventoryReportEntry, null);
        }
        
        /// <remarks/>
        public void CreateAsync(InventoryReportEntry InventoryReportEntry, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        InventoryReportEntry}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/inventoryreportentry:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref InventoryReportEntry[] InventoryReportEntry_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        InventoryReportEntry_List});
            InventoryReportEntry_List = ((InventoryReportEntry[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(InventoryReportEntry[] InventoryReportEntry_List) {
            this.CreateMultipleAsync(InventoryReportEntry_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(InventoryReportEntry[] InventoryReportEntry_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        InventoryReportEntry_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/inventoryreportentry:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref InventoryReportEntry InventoryReportEntry) {
            object[] results = this.Invoke("Update", new object[] {
                        InventoryReportEntry});
            InventoryReportEntry = ((InventoryReportEntry)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(InventoryReportEntry InventoryReportEntry) {
            this.UpdateAsync(InventoryReportEntry, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(InventoryReportEntry InventoryReportEntry, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        InventoryReportEntry}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/inventoryreportentry:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref InventoryReportEntry[] InventoryReportEntry_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        InventoryReportEntry_List});
            InventoryReportEntry_List = ((InventoryReportEntry[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(InventoryReportEntry[] InventoryReportEntry_List) {
            this.UpdateMultipleAsync(InventoryReportEntry_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(InventoryReportEntry[] InventoryReportEntry_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        InventoryReportEntry_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/inventoryreportentry:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key) {
            this.DeleteAsync(Key, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        Key}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry")]
    public partial class InventoryReportEntry {
        
        private string keyField;
        
        private Type typeField;
        
        private bool typeFieldSpecified;
        
        private string noField;
        
        private string descriptionField;
        
        private decimal inventoryField;
        
        private bool inventoryFieldSpecified;
        
        private decimal inventory_InterimField;
        
        private bool inventory_InterimFieldSpecified;
        
        private decimal wIP_InventoryField;
        
        private bool wIP_InventoryFieldSpecified;
        
        private decimal direct_Cost_Applied_ActualField;
        
        private bool direct_Cost_Applied_ActualFieldSpecified;
        
        private decimal overhead_Applied_ActualField;
        
        private bool overhead_Applied_ActualFieldSpecified;
        
        private decimal purchase_VarianceField;
        
        private bool purchase_VarianceFieldSpecified;
        
        private decimal inventory_AdjmtField;
        
        private bool inventory_AdjmtFieldSpecified;
        
        private decimal invt_Accrual_InterimField;
        
        private bool invt_Accrual_InterimFieldSpecified;
        
        private decimal cOGSField;
        
        private bool cOGSFieldSpecified;
        
        private decimal cOGS_InterimField;
        
        private bool cOGS_InterimFieldSpecified;
        
        private decimal material_VarianceField;
        
        private bool material_VarianceFieldSpecified;
        
        private decimal capacity_VarianceField;
        
        private bool capacity_VarianceFieldSpecified;
        
        private decimal subcontracted_VarianceField;
        
        private bool subcontracted_VarianceFieldSpecified;
        
        private decimal capacity_Overhead_VarianceField;
        
        private bool capacity_Overhead_VarianceFieldSpecified;
        
        private decimal mfg_Overhead_VarianceField;
        
        private bool mfg_Overhead_VarianceFieldSpecified;
        
        private decimal direct_Cost_Applied_WIPField;
        
        private bool direct_Cost_Applied_WIPFieldSpecified;
        
        private decimal overhead_Applied_WIPField;
        
        private bool overhead_Applied_WIPFieldSpecified;
        
        private decimal inventory_To_WIPField;
        
        private bool inventory_To_WIPFieldSpecified;
        
        private decimal wIP_To_InterimField;
        
        private bool wIP_To_InterimFieldSpecified;
        
        private decimal direct_Cost_AppliedField;
        
        private bool direct_Cost_AppliedFieldSpecified;
        
        private decimal overhead_AppliedField;
        
        private bool overhead_AppliedFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public Type Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal Inventory {
            get {
                return this.inventoryField;
            }
            set {
                this.inventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InventorySpecified {
            get {
                return this.inventoryFieldSpecified;
            }
            set {
                this.inventoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Inventory_Interim {
            get {
                return this.inventory_InterimField;
            }
            set {
                this.inventory_InterimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Inventory_InterimSpecified {
            get {
                return this.inventory_InterimFieldSpecified;
            }
            set {
                this.inventory_InterimFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal WIP_Inventory {
            get {
                return this.wIP_InventoryField;
            }
            set {
                this.wIP_InventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WIP_InventorySpecified {
            get {
                return this.wIP_InventoryFieldSpecified;
            }
            set {
                this.wIP_InventoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Direct_Cost_Applied_Actual {
            get {
                return this.direct_Cost_Applied_ActualField;
            }
            set {
                this.direct_Cost_Applied_ActualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Direct_Cost_Applied_ActualSpecified {
            get {
                return this.direct_Cost_Applied_ActualFieldSpecified;
            }
            set {
                this.direct_Cost_Applied_ActualFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Overhead_Applied_Actual {
            get {
                return this.overhead_Applied_ActualField;
            }
            set {
                this.overhead_Applied_ActualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Overhead_Applied_ActualSpecified {
            get {
                return this.overhead_Applied_ActualFieldSpecified;
            }
            set {
                this.overhead_Applied_ActualFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Purchase_Variance {
            get {
                return this.purchase_VarianceField;
            }
            set {
                this.purchase_VarianceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Purchase_VarianceSpecified {
            get {
                return this.purchase_VarianceFieldSpecified;
            }
            set {
                this.purchase_VarianceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Inventory_Adjmt {
            get {
                return this.inventory_AdjmtField;
            }
            set {
                this.inventory_AdjmtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Inventory_AdjmtSpecified {
            get {
                return this.inventory_AdjmtFieldSpecified;
            }
            set {
                this.inventory_AdjmtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Invt_Accrual_Interim {
            get {
                return this.invt_Accrual_InterimField;
            }
            set {
                this.invt_Accrual_InterimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Invt_Accrual_InterimSpecified {
            get {
                return this.invt_Accrual_InterimFieldSpecified;
            }
            set {
                this.invt_Accrual_InterimFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal COGS {
            get {
                return this.cOGSField;
            }
            set {
                this.cOGSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COGSSpecified {
            get {
                return this.cOGSFieldSpecified;
            }
            set {
                this.cOGSFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal COGS_Interim {
            get {
                return this.cOGS_InterimField;
            }
            set {
                this.cOGS_InterimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool COGS_InterimSpecified {
            get {
                return this.cOGS_InterimFieldSpecified;
            }
            set {
                this.cOGS_InterimFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Material_Variance {
            get {
                return this.material_VarianceField;
            }
            set {
                this.material_VarianceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Material_VarianceSpecified {
            get {
                return this.material_VarianceFieldSpecified;
            }
            set {
                this.material_VarianceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Capacity_Variance {
            get {
                return this.capacity_VarianceField;
            }
            set {
                this.capacity_VarianceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Capacity_VarianceSpecified {
            get {
                return this.capacity_VarianceFieldSpecified;
            }
            set {
                this.capacity_VarianceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Subcontracted_Variance {
            get {
                return this.subcontracted_VarianceField;
            }
            set {
                this.subcontracted_VarianceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Subcontracted_VarianceSpecified {
            get {
                return this.subcontracted_VarianceFieldSpecified;
            }
            set {
                this.subcontracted_VarianceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Capacity_Overhead_Variance {
            get {
                return this.capacity_Overhead_VarianceField;
            }
            set {
                this.capacity_Overhead_VarianceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Capacity_Overhead_VarianceSpecified {
            get {
                return this.capacity_Overhead_VarianceFieldSpecified;
            }
            set {
                this.capacity_Overhead_VarianceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Mfg_Overhead_Variance {
            get {
                return this.mfg_Overhead_VarianceField;
            }
            set {
                this.mfg_Overhead_VarianceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Mfg_Overhead_VarianceSpecified {
            get {
                return this.mfg_Overhead_VarianceFieldSpecified;
            }
            set {
                this.mfg_Overhead_VarianceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Direct_Cost_Applied_WIP {
            get {
                return this.direct_Cost_Applied_WIPField;
            }
            set {
                this.direct_Cost_Applied_WIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Direct_Cost_Applied_WIPSpecified {
            get {
                return this.direct_Cost_Applied_WIPFieldSpecified;
            }
            set {
                this.direct_Cost_Applied_WIPFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Overhead_Applied_WIP {
            get {
                return this.overhead_Applied_WIPField;
            }
            set {
                this.overhead_Applied_WIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Overhead_Applied_WIPSpecified {
            get {
                return this.overhead_Applied_WIPFieldSpecified;
            }
            set {
                this.overhead_Applied_WIPFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Inventory_To_WIP {
            get {
                return this.inventory_To_WIPField;
            }
            set {
                this.inventory_To_WIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Inventory_To_WIPSpecified {
            get {
                return this.inventory_To_WIPFieldSpecified;
            }
            set {
                this.inventory_To_WIPFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal WIP_To_Interim {
            get {
                return this.wIP_To_InterimField;
            }
            set {
                this.wIP_To_InterimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WIP_To_InterimSpecified {
            get {
                return this.wIP_To_InterimFieldSpecified;
            }
            set {
                this.wIP_To_InterimFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Direct_Cost_Applied {
            get {
                return this.direct_Cost_AppliedField;
            }
            set {
                this.direct_Cost_AppliedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Direct_Cost_AppliedSpecified {
            get {
                return this.direct_Cost_AppliedFieldSpecified;
            }
            set {
                this.direct_Cost_AppliedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Overhead_Applied {
            get {
                return this.overhead_AppliedField;
            }
            set {
                this.overhead_AppliedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Overhead_AppliedSpecified {
            get {
                return this.overhead_AppliedFieldSpecified;
            }
            set {
                this.overhead_AppliedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry")]
    public enum Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        G_L_Account,
        
        /// <remarks/>
        Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry")]
    public partial class InventoryReportEntry_Filter {
        
        private InventoryReportEntry_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public InventoryReportEntry_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/inventoryreportentry")]
    public enum InventoryReportEntry_Fields {
        
        /// <remarks/>
        Type,
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Inventory,
        
        /// <remarks/>
        Inventory_Interim,
        
        /// <remarks/>
        WIP_Inventory,
        
        /// <remarks/>
        Direct_Cost_Applied_Actual,
        
        /// <remarks/>
        Overhead_Applied_Actual,
        
        /// <remarks/>
        Purchase_Variance,
        
        /// <remarks/>
        Inventory_Adjmt,
        
        /// <remarks/>
        Invt_Accrual_Interim,
        
        /// <remarks/>
        COGS,
        
        /// <remarks/>
        COGS_Interim,
        
        /// <remarks/>
        Material_Variance,
        
        /// <remarks/>
        Capacity_Variance,
        
        /// <remarks/>
        Subcontracted_Variance,
        
        /// <remarks/>
        Capacity_Overhead_Variance,
        
        /// <remarks/>
        Mfg_Overhead_Variance,
        
        /// <remarks/>
        Direct_Cost_Applied_WIP,
        
        /// <remarks/>
        Overhead_Applied_WIP,
        
        /// <remarks/>
        Inventory_To_WIP,
        
        /// <remarks/>
        WIP_To_Interim,
        
        /// <remarks/>
        Direct_Cost_Applied,
        
        /// <remarks/>
        Overhead_Applied,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InventoryReportEntry Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InventoryReportEntry)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InventoryReportEntry Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InventoryReportEntry)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InventoryReportEntry[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InventoryReportEntry[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InventoryReportEntry InventoryReportEntry {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InventoryReportEntry)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InventoryReportEntry[] InventoryReportEntry_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InventoryReportEntry[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InventoryReportEntry InventoryReportEntry {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InventoryReportEntry)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public InventoryReportEntry[] InventoryReportEntry_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InventoryReportEntry[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591