//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace MsDynamicsTest.MsNavBlanketSalesOrder {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BlanketSalesOrder_Binding", Namespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder")]
    public partial class BlanketSalesOrder_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_SalesLinesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BlanketSalesOrder_Service() {
            this.Url = global::MsDynamicsTest.Properties.Settings.Default.MsDynamicsTest_MsNavBlanketSalesOrder_BlanketSalesOrder_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        public event Delete_SalesLinesCompletedEventHandler Delete_SalesLinesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/blanketsalesorder:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("BlanketSalesOrder")]
        public BlanketSalesOrder Read(string No) {
            object[] results = this.Invoke("Read", new object[] {
                        No});
            return ((BlanketSalesOrder)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string No) {
            this.ReadAsync(No, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string No, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        No}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/blanketsalesorder:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("BlanketSalesOrder")]
        public BlanketSalesOrder ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((BlanketSalesOrder)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/blanketsalesorder:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public BlanketSalesOrder[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] BlanketSalesOrder_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((BlanketSalesOrder[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(BlanketSalesOrder_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(BlanketSalesOrder_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/blanketsalesorder:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/blanketsalesorder:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/blanketsalesorder:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref BlanketSalesOrder BlanketSalesOrder) {
            object[] results = this.Invoke("Create", new object[] {
                        BlanketSalesOrder});
            BlanketSalesOrder = ((BlanketSalesOrder)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(BlanketSalesOrder BlanketSalesOrder) {
            this.CreateAsync(BlanketSalesOrder, null);
        }
        
        /// <remarks/>
        public void CreateAsync(BlanketSalesOrder BlanketSalesOrder, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        BlanketSalesOrder}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/blanketsalesorder:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref BlanketSalesOrder[] BlanketSalesOrder_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        BlanketSalesOrder_List});
            BlanketSalesOrder_List = ((BlanketSalesOrder[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(BlanketSalesOrder[] BlanketSalesOrder_List) {
            this.CreateMultipleAsync(BlanketSalesOrder_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(BlanketSalesOrder[] BlanketSalesOrder_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        BlanketSalesOrder_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/blanketsalesorder:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref BlanketSalesOrder BlanketSalesOrder) {
            object[] results = this.Invoke("Update", new object[] {
                        BlanketSalesOrder});
            BlanketSalesOrder = ((BlanketSalesOrder)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(BlanketSalesOrder BlanketSalesOrder) {
            this.UpdateAsync(BlanketSalesOrder, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(BlanketSalesOrder BlanketSalesOrder, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        BlanketSalesOrder}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/blanketsalesorder:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref BlanketSalesOrder[] BlanketSalesOrder_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        BlanketSalesOrder_List});
            BlanketSalesOrder_List = ((BlanketSalesOrder[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(BlanketSalesOrder[] BlanketSalesOrder_List) {
            this.UpdateMultipleAsync(BlanketSalesOrder_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(BlanketSalesOrder[] BlanketSalesOrder_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        BlanketSalesOrder_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/blanketsalesorder:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key) {
            this.DeleteAsync(Key, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        Key}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/blanketsalesorder:Delete_SalesLines", RequestNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", ResponseElementName="Delete_SalesLines_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_SalesLines_Result")]
        public bool Delete_SalesLines(string SalesLines_Key) {
            object[] results = this.Invoke("Delete_SalesLines", new object[] {
                        SalesLines_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_SalesLinesAsync(string SalesLines_Key) {
            this.Delete_SalesLinesAsync(SalesLines_Key, null);
        }
        
        /// <remarks/>
        public void Delete_SalesLinesAsync(string SalesLines_Key, object userState) {
            if ((this.Delete_SalesLinesOperationCompleted == null)) {
                this.Delete_SalesLinesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_SalesLinesOperationCompleted);
            }
            this.InvokeAsync("Delete_SalesLines", new object[] {
                        SalesLines_Key}, this.Delete_SalesLinesOperationCompleted, userState);
        }
        
        private void OnDelete_SalesLinesOperationCompleted(object arg) {
            if ((this.Delete_SalesLinesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_SalesLinesCompleted(this, new Delete_SalesLinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder")]
    public partial class BlanketSalesOrder {
        
        private string keyField;
        
        private string noField;
        
        private string sell_to_Customer_NoField;
        
        private string sell_to_Contact_NoField;
        
        private string sell_to_Customer_NameField;
        
        private string sell_to_AddressField;
        
        private string sell_to_Address_2Field;
        
        private string sell_to_Post_CodeField;
        
        private string sell_to_CityField;
        
        private string sell_to_ContactField;
        
        private System.DateTime order_DateField;
        
        private bool order_DateFieldSpecified;
        
        private System.DateTime document_DateField;
        
        private bool document_DateFieldSpecified;
        
        private string salesperson_CodeField;
        
        private string campaign_NoField;
        
        private string responsibility_CenterField;
        
        private string assigned_User_IDField;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private string bill_to_Customer_NoField;
        
        private string bill_to_Contact_NoField;
        
        private string bill_to_NameField;
        
        private string bill_to_AddressField;
        
        private string bill_to_Address_2Field;
        
        private string bill_to_Post_CodeField;
        
        private string bill_to_CityField;
        
        private string bill_to_ContactField;
        
        private string shortcut_Dimension_1_CodeField;
        
        private string shortcut_Dimension_2_CodeField;
        
        private string payment_Terms_CodeField;
        
        private System.DateTime due_DateField;
        
        private bool due_DateFieldSpecified;
        
        private decimal payment_Discount_PercentField;
        
        private bool payment_Discount_PercentFieldSpecified;
        
        private System.DateTime pmt_Discount_DateField;
        
        private bool pmt_Discount_DateFieldSpecified;
        
        private string payment_Method_CodeField;
        
        private bool prices_Including_VATField;
        
        private bool prices_Including_VATFieldSpecified;
        
        private string vAT_Bus_Posting_GroupField;
        
        private string ship_to_CodeField;
        
        private string ship_to_NameField;
        
        private string ship_to_AddressField;
        
        private string ship_to_Address_2Field;
        
        private string ship_to_Post_CodeField;
        
        private string ship_to_CityField;
        
        private string ship_to_ContactField;
        
        private string location_CodeField;
        
        private string shipment_Method_CodeField;
        
        private System.DateTime shipment_DateField;
        
        private bool shipment_DateFieldSpecified;
        
        private string currency_CodeField;
        
        private bool eU_3_Party_TradeField;
        
        private bool eU_3_Party_TradeFieldSpecified;
        
        private string transaction_TypeField;
        
        private string transaction_SpecificationField;
        
        private string transport_MethodField;
        
        private string exit_PointField;
        
        private string areaField;
        
        private Blanket_Sales_Order_Line[] salesLinesField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string Sell_to_Customer_No {
            get {
                return this.sell_to_Customer_NoField;
            }
            set {
                this.sell_to_Customer_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Sell_to_Contact_No {
            get {
                return this.sell_to_Contact_NoField;
            }
            set {
                this.sell_to_Contact_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Sell_to_Customer_Name {
            get {
                return this.sell_to_Customer_NameField;
            }
            set {
                this.sell_to_Customer_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Sell_to_Address {
            get {
                return this.sell_to_AddressField;
            }
            set {
                this.sell_to_AddressField = value;
            }
        }
        
        /// <remarks/>
        public string Sell_to_Address_2 {
            get {
                return this.sell_to_Address_2Field;
            }
            set {
                this.sell_to_Address_2Field = value;
            }
        }
        
        /// <remarks/>
        public string Sell_to_Post_Code {
            get {
                return this.sell_to_Post_CodeField;
            }
            set {
                this.sell_to_Post_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Sell_to_City {
            get {
                return this.sell_to_CityField;
            }
            set {
                this.sell_to_CityField = value;
            }
        }
        
        /// <remarks/>
        public string Sell_to_Contact {
            get {
                return this.sell_to_ContactField;
            }
            set {
                this.sell_to_ContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Order_Date {
            get {
                return this.order_DateField;
            }
            set {
                this.order_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Order_DateSpecified {
            get {
                return this.order_DateFieldSpecified;
            }
            set {
                this.order_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Document_Date {
            get {
                return this.document_DateField;
            }
            set {
                this.document_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Document_DateSpecified {
            get {
                return this.document_DateFieldSpecified;
            }
            set {
                this.document_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Salesperson_Code {
            get {
                return this.salesperson_CodeField;
            }
            set {
                this.salesperson_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Campaign_No {
            get {
                return this.campaign_NoField;
            }
            set {
                this.campaign_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Responsibility_Center {
            get {
                return this.responsibility_CenterField;
            }
            set {
                this.responsibility_CenterField = value;
            }
        }
        
        /// <remarks/>
        public string Assigned_User_ID {
            get {
                return this.assigned_User_IDField;
            }
            set {
                this.assigned_User_IDField = value;
            }
        }
        
        /// <remarks/>
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Bill_to_Customer_No {
            get {
                return this.bill_to_Customer_NoField;
            }
            set {
                this.bill_to_Customer_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Bill_to_Contact_No {
            get {
                return this.bill_to_Contact_NoField;
            }
            set {
                this.bill_to_Contact_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Bill_to_Name {
            get {
                return this.bill_to_NameField;
            }
            set {
                this.bill_to_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Bill_to_Address {
            get {
                return this.bill_to_AddressField;
            }
            set {
                this.bill_to_AddressField = value;
            }
        }
        
        /// <remarks/>
        public string Bill_to_Address_2 {
            get {
                return this.bill_to_Address_2Field;
            }
            set {
                this.bill_to_Address_2Field = value;
            }
        }
        
        /// <remarks/>
        public string Bill_to_Post_Code {
            get {
                return this.bill_to_Post_CodeField;
            }
            set {
                this.bill_to_Post_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Bill_to_City {
            get {
                return this.bill_to_CityField;
            }
            set {
                this.bill_to_CityField = value;
            }
        }
        
        /// <remarks/>
        public string Bill_to_Contact {
            get {
                return this.bill_to_ContactField;
            }
            set {
                this.bill_to_ContactField = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_1_Code {
            get {
                return this.shortcut_Dimension_1_CodeField;
            }
            set {
                this.shortcut_Dimension_1_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_2_Code {
            get {
                return this.shortcut_Dimension_2_CodeField;
            }
            set {
                this.shortcut_Dimension_2_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Payment_Terms_Code {
            get {
                return this.payment_Terms_CodeField;
            }
            set {
                this.payment_Terms_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Due_Date {
            get {
                return this.due_DateField;
            }
            set {
                this.due_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Due_DateSpecified {
            get {
                return this.due_DateFieldSpecified;
            }
            set {
                this.due_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Payment_Discount_Percent {
            get {
                return this.payment_Discount_PercentField;
            }
            set {
                this.payment_Discount_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Payment_Discount_PercentSpecified {
            get {
                return this.payment_Discount_PercentFieldSpecified;
            }
            set {
                this.payment_Discount_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Pmt_Discount_Date {
            get {
                return this.pmt_Discount_DateField;
            }
            set {
                this.pmt_Discount_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pmt_Discount_DateSpecified {
            get {
                return this.pmt_Discount_DateFieldSpecified;
            }
            set {
                this.pmt_Discount_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Payment_Method_Code {
            get {
                return this.payment_Method_CodeField;
            }
            set {
                this.payment_Method_CodeField = value;
            }
        }
        
        /// <remarks/>
        public bool Prices_Including_VAT {
            get {
                return this.prices_Including_VATField;
            }
            set {
                this.prices_Including_VATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Prices_Including_VATSpecified {
            get {
                return this.prices_Including_VATFieldSpecified;
            }
            set {
                this.prices_Including_VATFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string VAT_Bus_Posting_Group {
            get {
                return this.vAT_Bus_Posting_GroupField;
            }
            set {
                this.vAT_Bus_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Ship_to_Code {
            get {
                return this.ship_to_CodeField;
            }
            set {
                this.ship_to_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Ship_to_Name {
            get {
                return this.ship_to_NameField;
            }
            set {
                this.ship_to_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Ship_to_Address {
            get {
                return this.ship_to_AddressField;
            }
            set {
                this.ship_to_AddressField = value;
            }
        }
        
        /// <remarks/>
        public string Ship_to_Address_2 {
            get {
                return this.ship_to_Address_2Field;
            }
            set {
                this.ship_to_Address_2Field = value;
            }
        }
        
        /// <remarks/>
        public string Ship_to_Post_Code {
            get {
                return this.ship_to_Post_CodeField;
            }
            set {
                this.ship_to_Post_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Ship_to_City {
            get {
                return this.ship_to_CityField;
            }
            set {
                this.ship_to_CityField = value;
            }
        }
        
        /// <remarks/>
        public string Ship_to_Contact {
            get {
                return this.ship_to_ContactField;
            }
            set {
                this.ship_to_ContactField = value;
            }
        }
        
        /// <remarks/>
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shipment_Method_Code {
            get {
                return this.shipment_Method_CodeField;
            }
            set {
                this.shipment_Method_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Shipment_Date {
            get {
                return this.shipment_DateField;
            }
            set {
                this.shipment_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Shipment_DateSpecified {
            get {
                return this.shipment_DateFieldSpecified;
            }
            set {
                this.shipment_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Currency_Code {
            get {
                return this.currency_CodeField;
            }
            set {
                this.currency_CodeField = value;
            }
        }
        
        /// <remarks/>
        public bool EU_3_Party_Trade {
            get {
                return this.eU_3_Party_TradeField;
            }
            set {
                this.eU_3_Party_TradeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EU_3_Party_TradeSpecified {
            get {
                return this.eU_3_Party_TradeFieldSpecified;
            }
            set {
                this.eU_3_Party_TradeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Transaction_Type {
            get {
                return this.transaction_TypeField;
            }
            set {
                this.transaction_TypeField = value;
            }
        }
        
        /// <remarks/>
        public string Transaction_Specification {
            get {
                return this.transaction_SpecificationField;
            }
            set {
                this.transaction_SpecificationField = value;
            }
        }
        
        /// <remarks/>
        public string Transport_Method {
            get {
                return this.transport_MethodField;
            }
            set {
                this.transport_MethodField = value;
            }
        }
        
        /// <remarks/>
        public string Exit_Point {
            get {
                return this.exit_PointField;
            }
            set {
                this.exit_PointField = value;
            }
        }
        
        /// <remarks/>
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Blanket_Sales_Order_Line[] SalesLines {
            get {
                return this.salesLinesField;
            }
            set {
                this.salesLinesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder")]
    public enum Status {
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Released,
        
        /// <remarks/>
        Pending_Approval,
        
        /// <remarks/>
        Pending_Prepayment,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder")]
    public partial class Blanket_Sales_Order_Line {
        
        private string keyField;
        
        private Type typeField;
        
        private bool typeFieldSpecified;
        
        private string noField;
        
        private string cross_Reference_NoField;
        
        private string variant_CodeField;
        
        private string vAT_Prod_Posting_GroupField;
        
        private string descriptionField;
        
        private string location_CodeField;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private string work_Type_CodeField;
        
        private string unit_of_Measure_CodeField;
        
        private string unit_of_MeasureField;
        
        private decimal unit_Cost_LCYField;
        
        private bool unit_Cost_LCYFieldSpecified;
        
        private bool priceExistsField;
        
        private bool priceExistsFieldSpecified;
        
        private decimal unit_PriceField;
        
        private bool unit_PriceFieldSpecified;
        
        private decimal line_AmountField;
        
        private bool line_AmountFieldSpecified;
        
        private bool lineDiscExistsField;
        
        private bool lineDiscExistsFieldSpecified;
        
        private decimal line_Discount_PercentField;
        
        private bool line_Discount_PercentFieldSpecified;
        
        private decimal line_Discount_AmountField;
        
        private bool line_Discount_AmountFieldSpecified;
        
        private bool allow_Invoice_DiscField;
        
        private bool allow_Invoice_DiscFieldSpecified;
        
        private decimal qty_to_ShipField;
        
        private bool qty_to_ShipFieldSpecified;
        
        private decimal quantity_ShippedField;
        
        private bool quantity_ShippedFieldSpecified;
        
        private decimal quantity_InvoicedField;
        
        private bool quantity_InvoicedFieldSpecified;
        
        private System.DateTime shipment_DateField;
        
        private bool shipment_DateFieldSpecified;
        
        private string shortcut_Dimension_1_CodeField;
        
        private string shortcut_Dimension_2_CodeField;
        
        private string shortcutDimCode3Field;
        
        private string shortcutDimCode4Field;
        
        private string shortcutDimCode5Field;
        
        private string shortcutDimCode6Field;
        
        private string shortcutDimCode7Field;
        
        private string shortcutDimCode8Field;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public Type Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string Cross_Reference_No {
            get {
                return this.cross_Reference_NoField;
            }
            set {
                this.cross_Reference_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Variant_Code {
            get {
                return this.variant_CodeField;
            }
            set {
                this.variant_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string VAT_Prod_Posting_Group {
            get {
                return this.vAT_Prod_Posting_GroupField;
            }
            set {
                this.vAT_Prod_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Work_Type_Code {
            get {
                return this.work_Type_CodeField;
            }
            set {
                this.work_Type_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Unit_of_Measure_Code {
            get {
                return this.unit_of_Measure_CodeField;
            }
            set {
                this.unit_of_Measure_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Unit_of_Measure {
            get {
                return this.unit_of_MeasureField;
            }
            set {
                this.unit_of_MeasureField = value;
            }
        }
        
        /// <remarks/>
        public decimal Unit_Cost_LCY {
            get {
                return this.unit_Cost_LCYField;
            }
            set {
                this.unit_Cost_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_Cost_LCYSpecified {
            get {
                return this.unit_Cost_LCYFieldSpecified;
            }
            set {
                this.unit_Cost_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool PriceExists {
            get {
                return this.priceExistsField;
            }
            set {
                this.priceExistsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceExistsSpecified {
            get {
                return this.priceExistsFieldSpecified;
            }
            set {
                this.priceExistsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Unit_Price {
            get {
                return this.unit_PriceField;
            }
            set {
                this.unit_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_PriceSpecified {
            get {
                return this.unit_PriceFieldSpecified;
            }
            set {
                this.unit_PriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Line_Amount {
            get {
                return this.line_AmountField;
            }
            set {
                this.line_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Line_AmountSpecified {
            get {
                return this.line_AmountFieldSpecified;
            }
            set {
                this.line_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool LineDiscExists {
            get {
                return this.lineDiscExistsField;
            }
            set {
                this.lineDiscExistsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LineDiscExistsSpecified {
            get {
                return this.lineDiscExistsFieldSpecified;
            }
            set {
                this.lineDiscExistsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Line_Discount_Percent {
            get {
                return this.line_Discount_PercentField;
            }
            set {
                this.line_Discount_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Line_Discount_PercentSpecified {
            get {
                return this.line_Discount_PercentFieldSpecified;
            }
            set {
                this.line_Discount_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Line_Discount_Amount {
            get {
                return this.line_Discount_AmountField;
            }
            set {
                this.line_Discount_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Line_Discount_AmountSpecified {
            get {
                return this.line_Discount_AmountFieldSpecified;
            }
            set {
                this.line_Discount_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Allow_Invoice_Disc {
            get {
                return this.allow_Invoice_DiscField;
            }
            set {
                this.allow_Invoice_DiscField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Allow_Invoice_DiscSpecified {
            get {
                return this.allow_Invoice_DiscFieldSpecified;
            }
            set {
                this.allow_Invoice_DiscFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty_to_Ship {
            get {
                return this.qty_to_ShipField;
            }
            set {
                this.qty_to_ShipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Qty_to_ShipSpecified {
            get {
                return this.qty_to_ShipFieldSpecified;
            }
            set {
                this.qty_to_ShipFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity_Shipped {
            get {
                return this.quantity_ShippedField;
            }
            set {
                this.quantity_ShippedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Quantity_ShippedSpecified {
            get {
                return this.quantity_ShippedFieldSpecified;
            }
            set {
                this.quantity_ShippedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Quantity_Invoiced {
            get {
                return this.quantity_InvoicedField;
            }
            set {
                this.quantity_InvoicedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Quantity_InvoicedSpecified {
            get {
                return this.quantity_InvoicedFieldSpecified;
            }
            set {
                this.quantity_InvoicedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Shipment_Date {
            get {
                return this.shipment_DateField;
            }
            set {
                this.shipment_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Shipment_DateSpecified {
            get {
                return this.shipment_DateFieldSpecified;
            }
            set {
                this.shipment_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_1_Code {
            get {
                return this.shortcut_Dimension_1_CodeField;
            }
            set {
                this.shortcut_Dimension_1_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_2_Code {
            get {
                return this.shortcut_Dimension_2_CodeField;
            }
            set {
                this.shortcut_Dimension_2_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[3]")]
        public string ShortcutDimCode3 {
            get {
                return this.shortcutDimCode3Field;
            }
            set {
                this.shortcutDimCode3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[4]")]
        public string ShortcutDimCode4 {
            get {
                return this.shortcutDimCode4Field;
            }
            set {
                this.shortcutDimCode4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[5]")]
        public string ShortcutDimCode5 {
            get {
                return this.shortcutDimCode5Field;
            }
            set {
                this.shortcutDimCode5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[6]")]
        public string ShortcutDimCode6 {
            get {
                return this.shortcutDimCode6Field;
            }
            set {
                this.shortcutDimCode6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[7]")]
        public string ShortcutDimCode7 {
            get {
                return this.shortcutDimCode7Field;
            }
            set {
                this.shortcutDimCode7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShortcutDimCode[8]")]
        public string ShortcutDimCode8 {
            get {
                return this.shortcutDimCode8Field;
            }
            set {
                this.shortcutDimCode8Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder")]
    public enum Type {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        G_L_Account,
        
        /// <remarks/>
        Item,
        
        /// <remarks/>
        Resource,
        
        /// <remarks/>
        Fixed_Asset,
        
        /// <remarks/>
        Charge_Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder")]
    public partial class BlanketSalesOrder_Filter {
        
        private BlanketSalesOrder_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public BlanketSalesOrder_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/blanketsalesorder")]
    public enum BlanketSalesOrder_Fields {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Sell_to_Customer_No,
        
        /// <remarks/>
        Sell_to_Contact_No,
        
        /// <remarks/>
        Sell_to_Customer_Name,
        
        /// <remarks/>
        Sell_to_Address,
        
        /// <remarks/>
        Sell_to_Address_2,
        
        /// <remarks/>
        Sell_to_Post_Code,
        
        /// <remarks/>
        Sell_to_City,
        
        /// <remarks/>
        Sell_to_Contact,
        
        /// <remarks/>
        Order_Date,
        
        /// <remarks/>
        Document_Date,
        
        /// <remarks/>
        Salesperson_Code,
        
        /// <remarks/>
        Campaign_No,
        
        /// <remarks/>
        Responsibility_Center,
        
        /// <remarks/>
        Assigned_User_ID,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        Bill_to_Customer_No,
        
        /// <remarks/>
        Bill_to_Contact_No,
        
        /// <remarks/>
        Bill_to_Name,
        
        /// <remarks/>
        Bill_to_Address,
        
        /// <remarks/>
        Bill_to_Address_2,
        
        /// <remarks/>
        Bill_to_Post_Code,
        
        /// <remarks/>
        Bill_to_City,
        
        /// <remarks/>
        Bill_to_Contact,
        
        /// <remarks/>
        Shortcut_Dimension_1_Code,
        
        /// <remarks/>
        Shortcut_Dimension_2_Code,
        
        /// <remarks/>
        Payment_Terms_Code,
        
        /// <remarks/>
        Due_Date,
        
        /// <remarks/>
        Payment_Discount_Percent,
        
        /// <remarks/>
        Pmt_Discount_Date,
        
        /// <remarks/>
        Payment_Method_Code,
        
        /// <remarks/>
        Prices_Including_VAT,
        
        /// <remarks/>
        VAT_Bus_Posting_Group,
        
        /// <remarks/>
        Ship_to_Code,
        
        /// <remarks/>
        Ship_to_Name,
        
        /// <remarks/>
        Ship_to_Address,
        
        /// <remarks/>
        Ship_to_Address_2,
        
        /// <remarks/>
        Ship_to_Post_Code,
        
        /// <remarks/>
        Ship_to_City,
        
        /// <remarks/>
        Ship_to_Contact,
        
        /// <remarks/>
        Location_Code,
        
        /// <remarks/>
        Shipment_Method_Code,
        
        /// <remarks/>
        Shipment_Date,
        
        /// <remarks/>
        Currency_Code,
        
        /// <remarks/>
        EU_3_Party_Trade,
        
        /// <remarks/>
        Transaction_Type,
        
        /// <remarks/>
        Transaction_Specification,
        
        /// <remarks/>
        Transport_Method,
        
        /// <remarks/>
        Exit_Point,
        
        /// <remarks/>
        Area,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BlanketSalesOrder Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BlanketSalesOrder)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BlanketSalesOrder Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BlanketSalesOrder)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BlanketSalesOrder[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BlanketSalesOrder[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BlanketSalesOrder BlanketSalesOrder {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BlanketSalesOrder)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BlanketSalesOrder[] BlanketSalesOrder_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BlanketSalesOrder[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BlanketSalesOrder BlanketSalesOrder {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BlanketSalesOrder)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BlanketSalesOrder[] BlanketSalesOrder_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BlanketSalesOrder[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void Delete_SalesLinesCompletedEventHandler(object sender, Delete_SalesLinesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_SalesLinesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_SalesLinesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591